server:
  port: 8004

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.program.pyohemia.entity    # 所有Entity别名类所在包
logging:
  level:
    com:
      company:
        project:
          mapper: debug



  # 日志记录\输出配置

spring:
  datasource:

    driver-class-name: com.mysql.cj.jdbc.Driver            # mysql驱动包
    #    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://localhost:3306/pyohemia?&serverTimezone=UTC&useSSL=false            # 数据库名称
    #    url: jdbc:mysql://localhost:3306/pyohemia?useUnicode=yes&characterEncoding=utf8&useSSL=false              # 数据库名称
    username: root
    password: 123
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                    # 等待连接获取的最大超时时间
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    static-path-pattern: /static/**

